# Generated by Django 2.2.6 on 2020-01-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacityWeb', '0002_auto_20191128_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Wifi',
        ),
    ]
